// Code generated by "stringer -type=CommandType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[C_ARITHMETIC-0]
	_ = x[C_PUSH-1]
	_ = x[C_POP-2]
	_ = x[C_LABEL-3]
	_ = x[C_GOTO-4]
	_ = x[C_IF-5]
	_ = x[C_FUNCTION-6]
	_ = x[C_RETURN-7]
	_ = x[C_CALL-8]
}

const _CommandType_name = "C_ARITHMETICC_PUSHC_POPC_LABELC_GOTOC_IFC_FUNCTIONC_RETURNC_CALL"

var _CommandType_index = [...]uint8{0, 12, 18, 23, 30, 36, 40, 50, 58, 64}

func (i CommandType) String() string {
	if i < 0 || i >= CommandType(len(_CommandType_index)-1) {
		return "CommandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CommandType_name[_CommandType_index[i]:_CommandType_index[i+1]]
}
